# Generated by Django 5.0.6 on 2024-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(max_length=15)),
                ('number', models.IntegerField(max_length=15)),
                ('open', models.IntegerField(max_length=15)),
                ('high', models.IntegerField(max_length=15)),
                ('low', models.IntegerField(max_length=15)),
                ('close', models.IntegerField(max_length=15)),
                ('change', models.IntegerField(max_length=15)),
                ('transaction', models.IntegerField(max_length=15)),
            ],
        ),
    ]
